"""GET /kiro-spec/{job_id} — Return generated Kiro specification.
GET /kiro-spec/{job_id}/package — Download full .kiro package as zip.

Serves the Kiro spec markdown generated by the KiroAgent. Supports
both JSON (default) and text/markdown (via Accept header) responses.
Returns 404 if the job doesn't exist or hasn't completed yet.
"""

from __future__ import annotations

from uuid import UUID

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import PlainTextResponse, Response

from src.agents.kiro_package_builder import KiroPackageBuilder
from src.api.job_store import jobs
from src.domain.models.analysis_job import JobStatus

router = APIRouter(prefix="/kiro-spec", tags=["kiro-spec"])


@router.get(
    "/{job_id}",
    summary="Get Kiro specification for a completed analysis",
    status_code=status.HTTP_200_OK,
)
async def get_kiro_spec(job_id: UUID, request: Request):
    """Return the Kiro spec for a completed job.

    Returns markdown content. If Accept header includes text/markdown,
    returns as plain text with markdown content type. Otherwise returns
    a JSON wrapper.
    """
    job = jobs.get(job_id)
    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job {job_id} not found",
        )

    if job.status != JobStatus.COMPLETED:
        if job.kiro_spec is None:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Kiro spec for job {job_id} is not available yet (status: {job.status.value})",
            )

    spec_content = job.kiro_spec or ""

    # If client requests markdown directly, serve as plain text
    accept = request.headers.get("accept", "")
    if "text/markdown" in accept:
        return PlainTextResponse(
            content=spec_content,
            media_type="text/markdown",
        )

    # Default: JSON wrapper
    return {
        "jobId": str(job_id),
        "status": "completed",
        "markdown": spec_content,
    }


@router.get(
    "/{job_id}/package",
    summary="Download full .kiro package as zip",
    status_code=status.HTTP_200_OK,
)
async def download_kiro_package(job_id: UUID):
    """Download a complete .kiro package (zip) for import into Kiro IDE.

    The zip contains:
      specs/modernization/requirements.md
      specs/modernization/design.md
      specs/modernization/tasks.md
      hooks/post-modernization.json

    Returns application/zip with Content-Disposition attachment header.
    """
    job = jobs.get(job_id)
    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job {job_id} not found",
        )

    if job.status != JobStatus.COMPLETED:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Package for job {job_id} is not available yet (status: {job.status.value})",
        )

    # Extract project name from repo URL
    project_name = "project"
    if job.repo_url:
        parts = job.repo_url.rstrip("/").split("/")
        if parts:
            project_name = parts[-1]

    # Build the package
    builder = KiroPackageBuilder()
    zip_bytes = builder.build(
        project_name=project_name,
        kiro_spec=job.kiro_spec,
        architecture_report=job.architecture_report,
        modernization_plan=job.modernization_plan,
        quality_report=job.quality_report,
        security_report=job.security_report,
    )

    filename = f"kiro-spec-{project_name}.zip"

    return Response(
        content=zip_bytes,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
