"""GET /kiro-spec/{job_id} — Return generated Kiro specification.

Serves the Kiro spec markdown generated by the KiroAgent. Supports
both JSON (default) and text/markdown (via Accept header) responses.
Returns 404 if the job doesn't exist or hasn't completed yet.
"""

from __future__ import annotations

from uuid import UUID

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import PlainTextResponse

from src.api.job_store import jobs
from src.domain.models.analysis_job import JobStatus

router = APIRouter(prefix="/kiro-spec", tags=["kiro-spec"])


@router.get(
    "/{job_id}",
    summary="Get Kiro specification for a completed analysis",
    status_code=status.HTTP_200_OK,
)
async def get_kiro_spec(job_id: UUID, request: Request):
    """Return the Kiro spec for a completed job.

    Returns markdown content. If Accept header includes text/markdown,
    returns as plain text with markdown content type. Otherwise returns
    a JSON wrapper.
    """
    job = jobs.get(job_id)
    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job {job_id} not found",
        )

    if job.status != JobStatus.COMPLETED:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Job {job_id} has not completed yet (status: {job.status.value})",
        )

    spec_content = job.kiro_spec or ""

    # If client requests markdown directly, serve as plain text
    accept = request.headers.get("accept", "")
    if "text/markdown" in accept:
        return PlainTextResponse(
            content=spec_content,
            media_type="text/markdown",
        )

    # Default: JSON wrapper
    return {
        "jobId": str(job_id),
        "status": "completed",
        "markdown": spec_content,
    }
