"""GET /report/{job_id} — Return consolidated analysis report.

Serves the architecture, quality, security, documentation, and modernization
reports generated by the pipeline agents. Returns partial results while
the pipeline is still running (progressive disclosure).
"""

from __future__ import annotations

from uuid import UUID

from fastapi import APIRouter, HTTPException, status

from src.api.job_store import jobs
from src.domain.models.analysis_job import JobStatus

router = APIRouter(prefix="/report", tags=["report"])

# Statuses that indicate the job is active or done (results may be available)
_ACTIVE_STATUSES = {
    JobStatus.CLONING,
    JobStatus.ANALYZING,
    JobStatus.COMPLETED,
}


@router.get(
    "/{job_id}",
    summary="Get consolidated analysis report",
    status_code=status.HTTP_200_OK,
)
async def get_report(job_id: UUID) -> dict:
    """Return the analysis report for a job.

    Returns partial results while the pipeline is running. Each section
    is included only if the corresponding agent has completed.
    The 'complete' field indicates whether all agents have finished.
    """
    job = jobs.get(job_id)
    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job {job_id} not found",
        )

    if job.status == JobStatus.FAILED:
        # Still return whatever partial data we have
        pass
    elif job.status not in _ACTIVE_STATUSES:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Job {job_id} is in status '{job.status.value}' — no results available yet.",
        )

    return {
        "jobId": str(job_id),
        "status": job.status.value,
        "complete": job.status == JobStatus.COMPLETED,
        "architecture": job.architecture_report or {},
        "quality": job.quality_report or {},
        "security": job.security_report or {},
        "documentation": job.documentation_bundle or {},
        "modernization": job.modernization_plan or {},
    }
